qcacld-3.0: reduce tSirVersionString's size to 256
This was expanded with commit 80631484e537 ("qcacld-3.0: Add STT field in
firmware version").

The STT string cannot exceed 128 bytes, so use a more reasonable 256 bytes
as the size for tSirVersionString.

1024 is way too big and just 2 of them can trigger stack frame size limit
warning:

drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.c:7094:1: error: stack frame size of 2464 bytes in function 'wlan_hdd_cfg80211_get_wifi_info' [-Werror,-Wframe-larger-than=]

Fixes: 80631484e537 ("qcacld-3.0: Add STT field in firmware version")
Signed-off-by: Juhyung Park <qkrwngud825@gmail.com>